In [1]:
import torch

In [3]:
block_size = 8
n_embd = 32

#sinusoidal poistional embedding

In [13]:
x = torch.randint(1, 7, (4, 1))
y = torch.randint(1, 7, (8,))
print(x)
print(y)
x + y

tensor([[1],
        [1],
        [3],
        [5]])
tensor([1, 2, 6, 6, 6, 4, 1, 6])


tensor([[ 2,  3,  7,  7,  7,  5,  2,  7],
        [ 2,  3,  7,  7,  7,  5,  2,  7],
        [ 4,  5,  9,  9,  9,  7,  4,  9],
        [ 6,  7, 11, 11, 11,  9,  6, 11]])

In [18]:
pe = torch.zeros(block_size, n_embd)
pos = torch.arange(0, block_size, dtype=torch.float).unsqueeze(1)
pos

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])

In [15]:
import math

In [17]:
div = torch.exp(torch.arange(0, n_embd, 2).float() * (-math.log(10000.0) / n_embd))
div.shape

torch.Size([16])

In [20]:
div

tensor([1.0000e+00, 5.6234e-01, 3.1623e-01, 1.7783e-01, 1.0000e-01, 5.6234e-02,
        3.1623e-02, 1.7783e-02, 1.0000e-02, 5.6234e-03, 3.1623e-03, 1.7783e-03,
        1.0000e-03, 5.6234e-04, 3.1623e-04, 1.7783e-04])

In [21]:
pe[:, 0::2] = torch.sin(pos * div)
        # Apply cosine to odd indices in the positional encoding
pe[:, 1::2] = torch.cos(pos * div)

        # Add an extra dimension for batching (batch_size, seq_len, d_model)
pe = pe.unsqueeze(0)